name: Stale Issue Management

on:
  schedule:
    # Run daily at 3:17 AM UTC (avoid :00 times per best practices)
    - cron: '17 3 * * *'
  workflow_dispatch:
    # Allow manual trigger for testing

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - name: Mark stale issues and PRs
        uses: actions/stale@28ca1036281a5e5922ead5184a1bbf96e5fc984e # v9.0.0
        with:
          # Issue configuration
          days-before-issue-stale: 60
          days-before-issue-close: 7
          stale-issue-label: stale
          stale-issue-message: |
            This issue has been automatically marked as stale because it has not had recent activity.
            It will be closed in 7 days if no further activity occurs.

            If this issue is still relevant:
            - Comment to keep it open
            - Add the `pinned` label to prevent automatic closure

            Thank you for your contributions!
          close-issue-message: |
            This issue has been automatically closed due to inactivity.

            If this is still relevant, please:
            - Open a new issue with updated information
            - Reference this issue for context

            Thank you for your understanding!

          # PR configuration
          days-before-pr-stale: 30
          days-before-pr-close: 7
          stale-pr-label: stale
          stale-pr-message: |
            This pull request has been automatically marked as stale because it has not had recent activity.
            It will be closed in 7 days if no further activity occurs.

            If this PR is still in progress:
            - Comment or push new commits to keep it open
            - Add the `work-in-progress` label to prevent automatic closure

            Thank you for your contributions!
          close-pr-message: |
            This pull request has been automatically closed due to inactivity.

            If you'd like to continue this work:
            - Open a new PR with your changes
            - Reference this PR for context

            Thank you for your understanding!

          # Exemptions
          exempt-issue-labels: pinned,security,critical,blocked
          exempt-pr-labels: pinned,security,work-in-progress,blocked
          exempt-all-milestones: true
          exempt-all-assignees: true

          # Operations limit (GitHub API rate limiting)
          operations-per-run: 100

          # Debug mode (set to true for testing)
          debug-only: false
